/* What is inheritance? Give different types of inheritance.*/
-->Inheritance allows a class (child) to acquire properties and methods from another class (parent).
Types:
Single Inheritance: One parent, one child.
Multiple Inheritance: One child inherits from multiple parents.
Multilevel Inheritance: A child inherits from a parent, and this parent is a child of another parent.
Hierarchical Inheritance: Multiple children inherit from one parent.
Hybrid Inheritance: A combination of multiple and multilevel inheritance.